const languages = [
  "Arabic",
  "Chinese",
  "English",
  "French",
  "German",
  "Hindi",
  "Italian",
  "Japanese",
  "Polish",
  "Russian",
  "Spanish",
  "Ukrainian",
];
const states = [
  "Alexandria",
  "Aswan",
  "Asyut",
  "Beheira",
  "Beni suef",
  "Cairo",
  "Dakahlia",
  "Damietta",
  "Faiyum",
  "Gharbia",
  "Giza",
  "Helwan",
  "Ismaillia",
  "Kafr el-sheikh",
  "Luxor",
  "Matruh",
  "Minya",
  "Monufia",
  "New valley",
  "North sina",
  "Port said",
  "Qalyubia",
  "Qena",
  "Red sea",
  "Sharqia",
  "Sohag",
  "South sina",
  "Suez",
];
const language_levels = ["B1", "B2", "C1", "C2"];
export { languages, states, language_levels };
